DROP TABLE IF EXISTS birdNoise CASCADE;

CREATE TABLE IF NOT EXISTS birdNoise (
  id INTEGER AUTO_INCREMENT,
  poster VARCHAR(64) NOT NULL,
  timeCreated TIMESTAMP NOT NULL,
  content VARCHAR(256) NOT NULL,
  likes INTEGER NOT NULL DEFAULT(0),
  PRIMARY KEY(id)
);
